path:
    img2id_path: data/img2id.json
    train_path: data/e_train.json
    val_path: data/e_validation.json
    test_path: data/e_test.json
    image_path: data/image/
    emotion_id_path: data/emotion_dict.json
    
    train_preprocessed_path: data/train.pickle
    val_preprocessed_path: data/val.pickle
    test_preprocessed_path: data/test.pickle